### ISSUE TITLE
Unexpected behaviour of the agent trying to show a banner from a Jamf policy

### ISSUE THREAD

**Issue by SMartorelli** [IBM/mac-ibm-notifications#34]
**Describe the bug**
When calling the app from a script in Jamf, whether it is a banner or onboarding, the following error occurs.

`Mac@IBM Notification Agent rich notification autorization request ended with error: Couldn't communicate with a helper application.`

This only happens when the policy is run from Jamf directly (ex. recurring checkin policy) as far as I can tell. Running the script locally or calling the script from Terminal with the trigger for the policy seems to work ok.

**Desktop (please complete the following information):**
 - OS: macOS 11
 - Project version: 2.1.0

**Additional context**
This bug refers to [this discussion.](https://github.com/IBM/mac-ibm-notifications/discussions/28)

**Comment by SMartorelli** [comment]
The bug has been replicated and we're working on the fix

**Comment by SMartorelli** [comment]
Solution is currently in QA Process

**Comment by matt-taylor934** [comment]
I'm seeing the same issue with a popup window except the error is slightly different:

Unrecognized IBM Notifier launch attempt with arguments: %@.

Confirmed that running the launch code with the exact same arguments works fine manually in Terminal or when triggering then Jamf Pro Policy manually, only failing when originating from a system call such as a LaunchDaemon.

**Comment by SMartorelli** [comment]
Hi @matt-taylor934, make sure that in the script you use to trigger the pop-up you use the `sudo -u ${CURRENT_USER}` before the IBM Notifier binary path as showed in the script examples. You're right anyway because this is a workaround for this issue for pop-up UIs. The definitive fix, together with a lot of new features, will be release in the next 2/3 days ✌️

**Comment by matt-taylor934** [comment]
Thanks @SMartorelli, the workaround is great for the moment!

**Comment by dominicjaeckelleanix** [comment]
Hi @SMartorelli,

I'm having troubles in getting the pop-ups via JAMF to work. Even though it should be fixed.

I'm getting this error here:
`Script result: [31mRich notification autorization request ended with error: Couldn’t communicate with a helper application.[0m
`


That's the content of the script I'm using:
`#!/bin/bash
fullname=$(id -P $(stat -f%Su /dev/console) | awk -F '[:]' '{print $8}')
CURRENTUSER=$(ls -l /dev/console | awk '{print $3}')

sudo -u ${CURRENTUSER} "/Applications/LeanIX Notifier.app/Contents/MacOS/LeanIX Notifier" -type banner -title "Google Chrome Security Patch available" -subtitle "Hi $fullname, please go to the LeanIX Selfservice and install the latest Google Chrome update until the 30th of April 2022"`

Any advice?

Best,
Dominic

**Comment by dominicjaeckelleanix** [comment]
Hi @SMartorelli thanks for the quick answer, that worked but for some users I'm getting this error here now: 
`Rich notification autorization request ended with error: Notifications are not allowed for this application`

I double-checked, they definitely have the notifications profile installed. Any idea?

**Comment by SMartorelli** [comment]
We've also seen some inconsistency in the system loading new notification settings coming from a profile, it might solve itself after a reboot. Be sure that the bundle ids defined in the notification settings payload are the same of the new one you set for the rebranded app (if you rebranded it).

**Comment by marcusheBG** [comment]
Hello! August 22 2022 and we are getting "Rich notification authorization request ended with error: Notifications are not allowed for this application" when attempting to display a banner with a Jamf Check-In policy. We have tried using `sudo -u $current user` and even `launchctl asuser "$currentUserUID" sudo -u "$currentUser"` and the issue persists. We also tried adding a post install command / script of `"open /pathtoIBMNotifier" ` to see if the application just had to be opened once before being allowed to send notifications - but did not help. Some users are working properly.  We are unsure when it starts working. But a reboot could be it? Looks like this issue is still around. Will report back.

**Comment by SMartorelli** [comment]
@marcusheBG @dominicjaeckelleanix please check the solution found for this annoying issue https://github.com/IBM/mac-ibm-notifications/wiki/Known-Issues-And-Fixes#4-notification-agent-rich-notification-authorization-request-ended-with-error-notifications-are-not-allowed-for-this-application
